import Link from "next/link";
import type { Metadata } from "next";
import { SITE_NAME, ISSUES_URL } from "@/lib/site";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Terms",
  description: `The terms for using ${SITE_NAME} during beta — acceptable use, BYOK, availability, and liability.`,
  alternates: { canonical: "/terms" },
};

const UPDATED = "May 2026";

export default function TermsPage() {
  return (
    <div className="min-h-screen w-full">
      <div className="max-w-2xl mx-auto px-6 md:px-10 py-12 md:py-20">
        <Link
          href="/"
          className="mono text-[10px] uppercase tracking-widest"
          style={{ color: "#ff1744" }}
        >
          ← kerf.box
        </Link>

        <h1 className="serif text-3xl md:text-4xl mt-8 mb-2" style={{ fontWeight: 500 }}>
          Terms of use
        </h1>
        <p className="mono text-[10px] uppercase tracking-widest mb-10" style={{ color: "#7a7a82" }}>
          Last updated · {UPDATED}
        </p>

        <div className="space-y-8 text-sm leading-relaxed" style={{ color: "#cfc8ba" }}>
          <p>
            By using {SITE_NAME} you agree to these terms. {SITE_NAME} is a beta
            product offered as-is; the terms are intentionally short and may
            tighten as the product matures.
          </p>

          <section>
            <h2 className="serif text-xl mb-3" style={{ fontWeight: 500, color: "#f5f1e8" }}>
              The service
            </h2>
            <p>
              {SITE_NAME} generates marketing strategy artifacts (&ldquo;kerfs&rdquo;)
              and supporting copy. Output is generated by AI models and may be
              wrong, incomplete, or unsuitable for your situation. You are
              responsible for reviewing and validating anything you act on. Nothing
              produced here is legal, financial, or professional advice.
            </p>
          </section>

          <section>
            <h2 className="serif text-xl mb-3" style={{ fontWeight: 500, color: "#f5f1e8" }}>
              Acceptable use
            </h2>
            <ul className="space-y-2 list-disc pl-5">
              <li>
                Don&apos;t use the service to break the law, infringe others&apos;
                rights, or generate harmful, deceptive, or abusive material.
              </li>
              <li>
                Don&apos;t attempt to circumvent the per-IP rate limits, or probe
                the service for vulnerabilities without reporting them responsibly
                via{" "}
                <a
                  href={ISSUES_URL}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ color: "#ff1744" }}
                >
                  the issue tracker
                </a>
                .
              </li>
              <li>
                Keep your own AI provider key (BYOK) secret. You are responsible
                for any usage and charges incurred under your key; rotate it with
                your provider immediately if it leaks. {SITE_NAME} has no accounts
                and issues no API keys of its own.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="serif text-xl mb-3" style={{ fontWeight: 500, color: "#f5f1e8" }}>
              Bring your own key (BYOK)
            </h2>
            <p>
              When you supply your own API key — for Anthropic, OpenAI, Google,
              Moonshot, Alibaba, DeepSeek, Groq, OpenRouter, or any other
              provider — you are billed by that provider directly and are bound
              by that provider&apos;s terms for the usage. We pass your key
              through for the single request and never store it.
            </p>
          </section>

          <section>
            <h2 className="serif text-xl mb-3" style={{ fontWeight: 500, color: "#f5f1e8" }}>
              Availability &amp; changes
            </h2>
            <p>
              This is beta software. We may change, suspend, or discontinue
              features at any time, and we don&apos;t guarantee uptime, data
              durability, or that any particular feature will ship. {SITE_NAME} is
              free and account-free: saved kerfs live only in your browser, so
              keeping your own backups (export them as JSON) is on you.
            </p>
          </section>

          <section>
            <h2 className="serif text-xl mb-3" style={{ fontWeight: 500, color: "#f5f1e8" }}>
              Liability
            </h2>
            <p>
              To the maximum extent permitted by law, {SITE_NAME} is provided
              &ldquo;as is&rdquo; without warranties of any kind, and we are not
              liable for any indirect, incidental, or consequential damages arising
              from your use of the service or reliance on its output.
            </p>
          </section>

          <p className="text-xs" style={{ color: "#7a7a82" }}>
            Questions about these terms? Reach us via{" "}
            <a
              href={ISSUES_URL}
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#ff1744" }}
            >
              the issue tracker
            </a>
            . These terms are a good-faith starting point for a beta service, not a
            substitute for formal legal review of your own obligations.
          </p>
        </div>
      </div>
    </div>
  );
}
